// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "player1":return img`
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.........ccc...........
.........c42c..........
.......ccc44ccc........
.....cccc4444c2cc......
....c224244442422c.....
....c244224422442c.....
.....c4442222444f......
.....ff44444444ff......
.....fffbfeefbfff......
.....fff1fbbf1fff......
......ffbbbbbbff.......
......eefeeeefee.......
.....ebf242242cbe......
.....eef444444fee......
.......c244442c........
........ffffff.........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
